from diffusers import StableDiffusionPipeline, DEISMultistepScheduler
import torch
from PIL import Image


torch.cuda.empty_cache()

# 여기에 전체 텍스트 입력
txt = ['shinto shrine',
 'woman juggling',
 'stick figure with dress leaning left',
 'bridge at night',
 'kiss: woman, woman, dark skin tone, medium-dark skin tone',
 'regional indicator O',
 'woman golfing: light skin tone',
 'raised fist',
 'hand with index finger and thumb crossed: light skin tone',
 'women holding hands: medium skin tone, dark skin tone',
 'cyclone',
 'man running: medium-dark skin tone',
 'prohibited',
 'paintbrush',
 'person fencing',
 'coral',
 'writing hand: medium-dark skin tone',
 'martial arts uniform',
 'magic wand',
 'person: dark skin tone, blond hair',
 'man raising hand: light skin tone',
 'teddy bear',
 'deaf man: medium-dark skin tone',
 'bug',
 'heart decoration',
 'optical disk',
 'flag: Jersey',
 'woman: medium-light skin tone, bald',
 'vibration mode',
 'left arrow',
 'fearful face',
 'supervillain: medium-light skin tone',
 'hand with index finger and thumb crossed: medium skin tone',
 'palm down hand: light skin tone',
 'boule bread',
 'half orange fruit',
 'kiss: woman, man, medium skin tone, light skin tone',
 'Santa Claus: light skin tone',
 'woman with white cane: light skin tone',
 'man in motorized wheelchair: medium-dark skin tone',
 'red circle',
 'woman shrugging: medium-light skin tone',
 'technologist: dark skin tone',
 'man: medium skin tone, curly hair',
 'women holding hands: light skin tone',
 'man scientist: medium-dark skin tone',
 'heart hands: medium-dark skin tone',
 'person: medium skin tone, blond hair',
 'goal net',
 'thumbs down: medium-dark skin tone',
 'people holding hands: dark skin tone, medium skin tone',
 'cloud with lightning and rain',
 'ninja: light skin tone',
 'chocolate bar',
 'love hotel',
 'person in manual wheelchair: medium-light skin tone',
 'person feeding baby: medium-dark skin tone',
 'kiss: woman, woman, dark skin tone',
 'man in tuxedo',
 'kiss: woman, woman, light skin tone, medium-dark skin tone',
 'police officer: medium-dark skin tone',
 'chart increasing with yen',
 'flag: Guadeloupe',
 'handshake',
 'detective: medium-dark skin tone',
 'sleepy face',
 'smiling face with halo',
 'man construction worker',
 'oncoming taxi',
 'man firefighter',
 'man technologist: medium-light skin tone',
 'wilted flower',
 'people wrestling',
 'flag: Zambia',
 'up-pointing triangle with left half black',
 'handshake: medium-light skin tone, medium skin tone',
 'man factory worker: dark skin tone',
 'person gesturing NO: medium skin tone',
 'woman barista',
 'woman student: medium-dark skin tone',
 'police officer: medium-light skin tone',
 'men holding hands: medium-dark skin tone, dark skin tone',
 'person lifting weights: medium skin tone',
 'construction worker: dark skin tone',
 'judge: medium skin tone',
 'man with veil: dark skin tone',
 'page with curl',
 'man frowning: medium-dark skin tone',
 'farmer',
 'woman scientist: medium-dark skin tone',
 'person: medium skin tone, white hair',
 'Statue of Liberty',
 'cocktail glass',
 'face with crossed-out eyes',
 'instagram',
 'woman elf: dark skin tone',
 'woman walking',
 'stethoscope',
 'couple with heart: man, man, medium skin tone, medium-light skin tone',
 'woman mountain biking: medium skin tone',
 'woman golfing: medium skin tone',
 'mouse',
 'sun behind rain cloud',
 'man climbing: medium-dark skin tone',
 'tent',
 'wrench',
 'broccoli',
 'star',
 'flag: Northern Mariana Islands',
 'classical building',
 'woman getting massage',
 'kiss: man, man, medium-dark skin tone, dark skin tone',
 'deep red flag',
 'white vertical ellipse',
 'couple with heart: person, person, medium skin tone, dark skin tone',
 'flag: Togo',
 'person swimming',
 'tooth',
 'person surfing: medium-light skin tone',
 'pig nose',
 'palm down hand: medium-dark skin tone',
 'couple with heart: woman, woman, medium-dark skin tone, dark skin tone',
 'flag: Mongolia',
 'man getting haircut',
 'drunk person',
 'backhand index pointing right: light skin tone',
 'rainbow',
 'woman standing: medium-dark skin tone',
 'woman construction worker: light skin tone',
 'chipmunk',
 'man walking',
 'man lifting weights: medium-dark skin tone',
 'man cook',
 'berber flag',
 'fork and knife with plate',
 'gardening gloves',
 'nail polish',
 'clapping hands: light skin tone',
 'woman kneeling: light skin tone',
 'elevator',
 'green heart',
 'flag: Micronesia',
 'shelter',
 'child: medium-dark skin tone',
 'person surfing',
 'mermaid: medium-light skin tone',
 'ribbon',
 'man with white cane: medium skin tone',
 'tram car',
 'woman: dark skin tone, red hair',
 'annoyed face with tongue',
 'leftwards hand: medium-light skin tone',
 'person playing handball: medium skin tone',
 'avocado',
 'person with veil: light skin tone',
 'water pistol',
 'circled M',
 'couple with heart: man, man, light skin tone, medium skin tone',
 'sun with face',
 'princess: dark skin tone',
 'flag: Turks & Caicos Islands',
 'woman and man holding hands: medium-light skin tone, light skin tone',
 'television',
 'Greta Thunberg',
 'man: dark skin tone, blond hair',
 'woman: dark skin tone, bald',
 'file cabinet',
 'love-you gesture: medium skin tone',
 'man gesturing OK: dark skin tone',
 'rainbow flag',
 'handshake: medium skin tone, light skin tone',
 'footprints',
 'man fairy',
 'red exclamation mark',
 'middle finger: dark skin tone',
 'leg',
 'selfie: medium-light skin tone',
 'person juggling: dark skin tone',
 'person biking: medium-dark skin tone',
 'person bouncing ball: light skin tone',
 'horse',
 'dodo',
 'hiking boot',
 'kehrwoche',
 'hand with fingers splayed: dark skin tone',
 'people holding hands: medium-light skin tone, dark skin tone',
 'person raising hand: medium-dark skin tone',
 'construction worker',
 'flag: Jamaica',
 'astronaut: dark skin tone',
 'person in suit levitating: medium-dark skin tone',
 'brown hexagon',
 'flag: St. Martin',
 'mx claus',
 'ninja: medium skin tone',
 'man frowning: medium-light skin tone',
 'man lifting weights',
 'woman: medium skin tone, red hair',
 'snowboarder',
 'sign of the horns: light skin tone',
 'chains',
 'girl: medium-light skin tone',
 'woman mage: dark skin tone',
 'man firefighter: medium-light skin tone',
 'bubbles',
 'nose: medium-dark skin tone',
 'pouring liquid',
 'technologist: light skin tone',
 'man elf: medium-light skin tone',
 'double tap',
 'woman health worker: medium-dark skin tone',
 'left-facing fist: medium-light skin tone',
 'oncoming police car',
 'man in lotus position: medium skin tone',
 'teacher: dark skin tone',
 'person lifting weights: light skin tone',
 'deaf man: medium-light skin tone',
 'iceberg',
 'woman health worker: medium skin tone',
 'handshake: dark skin tone, medium-dark skin tone',
 'jar',
 'woman standing: medium skin tone',
 'no littering',
 'goat',
 'man with white cane: dark skin tone',
 'keycap: 5',
 'flag: United Nations',
 'ninja',
 'hindu temple',
 'locomotion',
 'woman with white cane: medium skin tone',
 'diamond suit',
 'badger',
 'flag: Iraq',
 'Japanese “reserved” button',
 'ninja: medium-light skin tone',
 'man supervillain',
 'flag: Guyana',
 'ear',
 'woman shrugging: medium skin tone',
 'man lifting weights: medium skin tone',
 'Japanese “passing grade” button',
 'Pisces',
 'large intestine',
 'nose',
 'palms up together: light skin tone',
 'troll',
 'flag: Greece',
 'person kneeling',
 'bed',
 'love-you gesture: medium-dark skin tone',
 'globe showing Asia-Australia',
 'flag: Honduras',
 'man lifting weights: light skin tone',
 'rose',
 'office worker',
 'old man: dark skin tone',
 'check mark',
 'bikini',
 'flag: Hong Kong SAR China',
 'cafeteria',
 'ear with hearing aid: dark skin tone',
 'woman cartwheeling: medium-light skin tone',
 'flag: Czechia',
 'person with crown: light skin tone',
 'student: light skin tone',
 'person: light skin tone, red hair',
 'couple with heart: man, man, medium-light skin tone',
 'fuel pump',
 'heart suit',
 'red triangle pointed down',
 'people holding hands: dark skin tone, light skin tone',
 'woman and man holding hands: dark skin tone',
 'dotted six-pointed star',
 'wine glass',
 'NEW button',
 'person climbing: dark skin tone',
 'couple with heart: woman, woman, medium-dark skin tone',
 'person feeding baby: medium-light skin tone',
 'kiss: woman, woman, medium-light skin tone',
 'man cartwheeling: dark skin tone',
 'pigeon',
 'flag: Oman',
 'bank',
 'people holding hands: dark skin tone',
 'drum',
 'dog',
 'flag: India',
 'flag: Uzbekistan',
 'man with veil: medium skin tone',
 'volcano ashes',
 'woman and man holding hands: medium-dark skin tone, medium skin tone',
 'couple with heart: person, person, medium-dark skin tone, dark skin tone',
 'person golfing: medium skin tone',
 'woman teacher: medium-light skin tone',
 'flag: Tuvalu',
 'rice ball',
 'wastebasket',
 'man in lotus position: medium-light skin tone',
 'pie',
 'sparkle',
 'woman fairy: dark skin tone',
 'flag: Timor-Leste',
 'call me hand',
 'blue circle',
 'farmer: medium-light skin tone',
 'flag: Burkina Faso',
 'woman gesturing OK: medium skin tone',
 'person in manual wheelchair',
 'superhero: light skin tone',
 'square with upper left diagonal black',
 'couple with heart: man, man, medium-dark skin tone, medium-light skin tone',
 'arrow turn right',
 'man: white hair',
 'person with skullcap: medium-light skin tone',
 'woman bowing: medium skin tone',
 'fairy',
 'grimacing face',
 'man bouncing ball: light skin tone',
 'person with crown: dark skin tone',
 'farmer: dark skin tone',
 'woman mechanic: medium-light skin tone',
 'man farmer: medium-light skin tone',
 'man pilot: light skin tone',
 'flag: Kosovo',
 'bicycle',
 'floating ice',
 'man police officer: medium-dark skin tone',
 'flag: Austria',
 'woman in steamy room',
 'double curly loop',
 'woman construction worker: dark skin tone',
 'control knobs',
 'nail polish: medium-dark skin tone',
 'memo',
 'woman standing: dark skin tone',
 'cigarette',
 'man standing: medium skin tone',
 'person biking',
 'leg: light skin tone',
 'person wearing turban: dark skin tone',
 'Japanese “application” button',
 'left-facing fist: medium skin tone',
 'family: man, woman, boy, boy',
 'woman elf: medium-light skin tone',
 'oil drum',
 'flag: Luxembourg',
 'person cartwheeling: medium-light skin tone',
 'water closet',
 'eject button',
 'doughnut',
 'woman singer: medium skin tone',
 'flag: Montserrat',
 'person: blond hair',
 'led',
 'beetle',
 'melon',
 'glowing star',
 'astronaut',
 'sparkling heart',
 'waning crescent moon',
 'baby: light skin tone',
 'man health worker: light skin tone',
 'down-right arrow',
 'child: dark skin tone',
 'flag: Malta',
 'woman dancing',
 'love-you gesture',
 'person tipping hand: medium-light skin tone',
 'woman technologist',
 'black cat',
 'speaker low volume',
 'man swimming: medium-light skin tone',
 'victory hand: medium-dark skin tone',
 'kiss: person, person, medium-light skin tone, medium skin tone',
 'link',
 'person: medium skin tone, curly hair',
 'person wearing turban: medium-light skin tone',
 'timer',
 'flag: Lithuania',
 'fishing pole',
 'person: dark skin tone, white hair',
 'graduation cap',
 'couple with heart: person, person, light skin tone, medium skin tone',
 'middle finger: medium-dark skin tone',
 'merman',
 'sound recording copyright',
 'judge',
 'Chrome',
 'leafy green',
 'tennis',
 'man swimming: dark skin tone',
 'man playing water polo',
 'top hat',
 'pizza',
 'bread',
 'flag: Cyprus',
 'person bouncing ball: dark skin tone',
 'kiss: woman, man, dark skin tone, light skin tone',
 'person walking: medium-light skin tone',
 'diving mask',
 'woman singer: medium-dark skin tone',
 'person feeding baby: light skin tone',
 'two hearts',
 'flag: Israel',
 'outbox tray',
 'person pouting: dark skin tone',
 'keyboard',
 'sleeping face',
 'man playing water polo: dark skin tone',
 'tongue',
 'flag: Nauru',
 'flag: Gibraltar',
 'man tipping hand: medium skin tone',
 'woman mechanic: medium skin tone',
 'clockwise vertical arrows',
 'slightly frowning face',
 'flamingo',
 'cat with tears of joy',
 'zipper-mouth face',
 'mantelpiece clock',
 'handshake: light skin tone',
 'person in tuxedo: medium-dark skin tone',
 'flag: North Korea',
 'man mage: light skin tone',
 'flag: Central African Republic',
 'hole',
 'man running: medium-light skin tone',
 'woman elf: medium skin tone',
 'supervillain: light skin tone',
 'hammer and pick',
 'ID button',
 'moon viewing ceremony',
 'couple with heart: person, person, dark skin tone, light skin tone',
 'gem stone',
 'person with skullcap: dark skin tone',
 'confetti ball',
 'man dancing: medium-dark skin tone',
 'flag: Niue',
 'woman: medium skin tone, curly hair',
 'thumbs up',
 'backhand index pointing left: medium-light skin tone',
 'department store',
 'polar explorer',
 'family: man, man, boy, boy',
 'kiss: man, man, dark skin tone',
 'person running: dark skin tone',
 'flag: Mexico',
 'pig',
 'woman wearing turban: medium skin tone',
 'atom symbol',
 'call me hand: medium-light skin tone',
 'dizzy',
 'kiss: woman, woman, light skin tone',
 'mark',
 'woman: light skin tone',
 'flag: Eswatini',
 'person in bed: dark skin tone',
 'woman health worker: medium-light skin tone',
 'military helmet',
 'spouting whale',
 'flag: Tokelau',
 'people holding hands: medium-dark skin tone, medium-light skin tone',
 'purple heart',
 'couple with heart: woman, woman',
 'woman raising hand',
 'service dog',
 'woman: medium skin tone, white hair',
 'kiss: man, man, medium-light skin tone, medium-dark skin tone',
 'palm down hand: medium skin tone',
 'woman lifting weights: medium-light skin tone',
 'warning fire',
 'thumbs down: dark skin tone',
 'flag: El Salvador',
 'skull and crossbones',
 'man: medium-dark skin tone, blond hair',
 'men holding hands: light skin tone, dark skin tone',
 'man factory worker: medium-light skin tone',
 'man tipping hand: medium-light skin tone',
 'woman scientist: dark skin tone',
 'stopwatch',
 'person in suit levitating: dark skin tone',
 'berlin flag',
 'person with white cane: dark skin tone',
 'woman fairy: medium skin tone',
 'circled cc',
 'person playing handball: medium-light skin tone',
 'aerial tramway',
 'person bowing',
 'woman bouncing ball',
 'cook: medium-dark skin tone',
 'woman dancing: medium-light skin tone',
 'penguin',
 'woman: white hair',
 'person: light skin tone, curly hair',
 'family',
 'deaf woman',
 'backhand index pointing down: medium-dark skin tone',
 'unicorn',
 'kiss: woman, man, light skin tone, dark skin tone',
 'person cartwheeling: medium skin tone',
 'kiss: woman, woman, medium-light skin tone, light skin tone',
 'kiss: woman, man, medium skin tone, dark skin tone',
 'Twitter',
 'person in lotus position',
 'authority instruction',
 'no entry',
 'woman artist: medium skin tone',
 'man feeding baby: light skin tone',
 'vampire: medium-light skin tone',
 'leftwards hand: medium-dark skin tone',
 'woman and man holding hands: light skin tone, medium-dark skin tone',
 'wheel',
 'revolving hearts',
 'sun behind large cloud',
 'basque flag',
 'clapping hands',
 'dollar banknote',
 'green circle',
 'cheese wedge',
 'kiss: woman, man, dark skin tone, medium skin tone',
 'incredulous face',
 'cricket game',
 'face with diagonal mouth',
 'desert',
 'unlocked',
 'unamused face',
 'stick figure',
 'man in lotus position: dark skin tone',
 'man bowing: medium skin tone',
 'person in steamy room: medium-light skin tone',
 'watch',
 'zany face',
 'right-facing fist: dark skin tone',
 'old man: medium-light skin tone',
 'woman’s boot',
 'drone',
 'place of worship',
 'sanitizer spray',
 'hand with fingers splayed',
 'selfie',
 'trade mark',
 'prince: dark skin tone',
 'delivery truck',
 'person: light skin tone, white hair',
 'locomotive',
 'woman facepalming: medium skin tone',
 'flag: Anguilla',
 'scale',
 'woman in tuxedo: medium skin tone',
 'man in tuxedo: light skin tone',
 'man in lotus position: medium-dark skin tone',
 'woman dancing: medium-dark skin tone',
 'square with right half black',
 'man in steamy room: medium skin tone',
 'flag: South Sudan',
 'esperanto flag',
 'old man: medium skin tone',
 'palms up together: medium skin tone',
 'person: medium-light skin tone, bald',
 'student',
 'artist: light skin tone',
 'woman superhero: medium skin tone',
 'flag: Montenegro',
 'regional indicator P',
 'pixelfed',
 'woman in motorized wheelchair: medium-light skin tone',
 'flag: Ceuta & Melilla',
 'man superhero: light skin tone',
 'woman bouncing ball: dark skin tone',
 'confounded face',
 'man golfing: light skin tone',
 'giraffe',
 'joint pain',
 'backhand index pointing right: medium skin tone',
 'nail polish: medium-light skin tone',
 'person walking: medium skin tone',
 'rooster',
 'mermaid: medium-dark skin tone',
 'flag: Barbados',
 'eight-spoked asterisk',
 'grinning face',
 'raised fist: light skin tone',
 'axe',
 'woman student: light skin tone',
 'bust in silhouette',
 'woman in tuxedo: medium-dark skin tone',
 'facebook',
 'weary face',
 'handshake: dark skin tone, medium skin tone',
 'woman feeding baby: dark skin tone',
 'woman playing handball: medium-dark skin tone',
 'axe',
 'men holding hands: medium-light skin tone, medium-dark skin tone',
 'woman swimming: medium-dark skin tone',
 'flag: Cocos (Keeling) Islands',
 'details',
 'couple with heart: man, man, medium-dark skin tone, light skin tone',
 'person golfing: light skin tone',
 'Scorpio',
 'saluting face',
 'pinching hand: light skin tone',
 'jar with blue content',
 'woman: medium-dark skin tone, white hair',
 'teacup without handle',
 'family: man, woman, girl, boy',
 'kiss: man, man, dark skin tone, medium-dark skin tone',
 'supervillain: medium-dark skin tone',
 'woman and man holding hands: medium skin tone, light skin tone',
 'deep yellow flag',
 'rock',
 'superhero: medium-dark skin tone',
 'police officer: light skin tone',
 'woman police officer',
 'narwhal',
 'man mechanic: medium skin tone',
 'person: light skin tone, bald',
 'baby symbol',
 'railway car',
 'flag: British Virgin Islands',
 'hippopotamus',
 'person biking: medium-light skin tone',
 'mouth',
 'person pouting: medium-dark skin tone',
 'panda',
 'man: light skin tone, beard',
 'woman and man holding hands: medium skin tone',
 'kiss: woman, woman, medium-dark skin tone',
 'flagged point',
 'couple with heart: person, person, medium skin tone, light skin tone',
 'information',
 'woman gesturing OK: dark skin tone',
 'woman teacher: medium-dark skin tone',
 'smiling face with open hands',
 'man artist: dark skin tone',
 'man mechanic: dark skin tone',
 'person shrugging: light skin tone',
 'raising hands: medium skin tone',
 'man mountain biking: dark skin tone',
 'sandwich',
 'circled equals',
 'OK hand: light skin tone',
 'barista',
 'seedling',
 'person in tuxedo',
 'polar research station',
 'woman and man holding hands: light skin tone, dark skin tone',
 'woman gesturing NO',
 'backhand index pointing right',
 'four-thirty',
 'teacher',
 'Japanese “here” button',
 'Chromium',
 'kiss: man, man, medium skin tone, medium-light skin tone',
 'woman judge: medium-light skin tone',
 'student: medium skin tone',
 'notebook',
 'regional indicator Y',
 'person getting haircut: dark skin tone',
 'card index',
 'flag: Zimbabwe',
 'fast up button',
 'man kneeling: light skin tone',
 'woman police officer: medium skin tone',
 'woman vampire: dark skin tone',
 'input latin lowercase',
 'palm down hand: dark skin tone',
 'part alternation mark',
 'nauseated face',
 'person getting massage',
 'OK hand',
 'flag: Norway',
 'man supervillain: medium-dark skin tone',
 'service mark',
 'sneezing face',
 'man artist: medium skin tone',
 'forceps',
 'black star',
 'woman in manual wheelchair: medium skin tone',
 'black heart',
 'wedding',
 'health worker: medium-dark skin tone',
 'polar explorer woman',
 'factory worker: medium skin tone',
 'woman wearing turban: medium-dark skin tone',
 'compass',
 'backhand index pointing up',
 'judge: light skin tone',
 'power symbol',
 'woman getting haircut',
 'baby chick',
 'person shrugging: medium-light skin tone',
 'rightwards hand: dark skin tone',
 'man student: light skin tone',
 '1st place medal',
 'person bouncing ball: medium-dark skin tone',
 'flag: Solomon Islands',
 'office building',
 'firefighter',
 'motor',
 'woman feeding baby: medium-dark skin tone',
 'person in lotus position: medium-light skin tone',
 'couple with heart: woman, man, medium-light skin tone, light skin tone',
 'people with bunny ears',
 'nose: medium-light skin tone',
 'cake',
 'prince: medium skin tone',
 'person kneeling: medium-dark skin tone',
 'man raising hand: medium-light skin tone',
 'couple with heart: person, person, medium skin tone, medium-dark skin tone',
 'man tipping hand: medium-dark skin tone',
 'woman with medical mask',
 'schwäbisch gmünd fünfknopfturm',
 'space shuttle',
 'anguished face',
 'woman construction worker: medium-dark skin tone',
 'guard: medium-dark skin tone',
 'angry face',
 'cat',
 'Santa Claus: medium-dark skin tone',
 'parrot',
 'flag: Tanzania',
 'couple with heart: woman, man, medium-dark skin tone, medium skin tone',
 'Taurus',
 'globe with meridians',
 'flag: Italy',
 'couple with heart: woman, man, medium skin tone, medium-dark skin tone',
 'kiss: person, person, medium skin tone, medium-dark skin tone',
 'END arrow',
 'person bowing: dark skin tone',
 'man lifting weights: medium-light skin tone',
 'index pointing at the viewer: medium-light skin tone',
 'flag: Antarctica',
 'keycap: 7',
 'dove',
 'kiss mark',
 'hand with fingers splayed: medium-dark skin tone',
 'share',
 'kiss: person, person, medium-dark skin tone, medium-light skin tone',
 'woman mountain biking: medium-dark skin tone',
 'regional indicator H',
 'sign of the horns: medium-dark skin tone',
 'woman pouting: medium-dark skin tone',
 'handshake: dark skin tone',
 'woman vampire: medium-dark skin tone',
 'children crossing',
 'person in bed',
 'left right black arrow',
 'mate',
 'nose: dark skin tone',
 'couple with heart: person, person, light skin tone, medium-dark skin tone',
 'kiss: man, man, dark skin tone, medium-light skin tone',
 'man mechanic: medium-dark skin tone',
 'backhand index pointing right: medium-dark skin tone',
 'person: red hair',
 'volleyball',
 'people holding hands',
 'man wearing turban: medium-light skin tone',
 'sauropod',
 'collision',
 'add contact',
 'flag: Ethiopia',
 'kiss: woman, man, medium-dark skin tone, dark skin tone',
 'woman in tuxedo: light skin tone',
 'sloth',
 'money bag',
 'honeybee',
 'woman superhero: light skin tone',
 'twelve-thirty',
 'beluga',
 'person kneeling: light skin tone',
 'foot',
 'index pointing at the viewer: medium skin tone',
 'woman scientist: medium skin tone',
 'person getting haircut',
 'foot: light skin tone',
 'man singer: dark skin tone',
 'oil spill',
 'pregnant person: dark skin tone',
 'backhand index pointing down: medium-light skin tone',
 'heart hands',
 'man detective: medium skin tone',
 'hammer and wrench',
 'woman with veil',
 'bus stop',
 'infinity',
 'backpack',
 'people holding hands: medium-light skin tone',
 'crystal ball',
 'seven-thirty',
 'oncoming fist',
 'person gesturing OK: light skin tone',
 'rightwards hand: medium-light skin tone',
 'hand with index finger and thumb crossed: medium-dark skin tone',
 'man climbing',
 'backhand index pointing up: dark skin tone',
 'woman in motorized wheelchair: dark skin tone',
 'arduino',
 'dark skin tone',
 'movie camera',
 'flag: Cameroon',
 'family: woman, girl',
 'chicken',
 'man teacher',
 'flag: Bosnia & Herzegovina',
 'pineapple',
 'keycap: 0',
 'open mailbox with lowered flag',
 'baby angel: medium-dark skin tone',
 'hot face',
 'male nurse',
 'couple with heart: woman, man, medium-dark skin tone, light skin tone',
 'man: medium-light skin tone, red hair',
 'no stencil',
 'man astronaut: dark skin tone',
 'flag: Armenia',
 'flag: Albania',
 'kiss: woman, man, medium skin tone, medium-light skin tone',
 'woman bowing: medium-light skin tone',
 'health worker: medium-light skin tone',
 'deep green flag',
 'grinning squinting face',
 'man singer: medium-dark skin tone',
 'mage: light skin tone',
 'woman tipping hand',
 'diya lamp',
 'face with thermometer',
 'thumbs down: medium-light skin tone',
 'geiger counter',
 'dango',
 'kiss: woman, woman, light skin tone, dark skin tone',
 'hedgehog',
 'face with monocle',
 'confused face',
 'mechanic: dark skin tone',
 'filter',
 'handshake: medium-light skin tone',
 'flag: Namibia',
 'auto rickshaw',
 'flashlight',
 'gloves',
 'man biking',
 'women holding hands: medium skin tone, medium-light skin tone',
 'overlapping white and black squares',
 'couple with heart: woman, man, dark skin tone',
 'construction worker: light skin tone',
 'french press',
 'couple with heart: person, person, light skin tone, medium-light skin tone',
 'man feeding baby',
 'man: medium-dark skin tone, white hair',
 'next track button',
 'eleven-thirty',
 'american football',
 'palm up hand',
 'woman lifting weights: dark skin tone',
 'men holding hands: medium-dark skin tone, medium-light skin tone',
 'pushpin',
 'man farmer: dark skin tone',
 'palm up hand: medium-dark skin tone',
 'woman office worker: medium-light skin tone',
 'man raising hand',
 'elf',
 'man: light skin tone, curly hair',
 'superhero: medium-light skin tone',
 'flag: Brazil',
 'closed umbrella',
 'jar with green content',
 'person mountain biking: medium skin tone',
 'person bouncing ball: medium-light skin tone',
 'hamburger',
 'flag: Monaco',
 'man in manual wheelchair: medium-dark skin tone',
 'kiss: person, person, light skin tone, dark skin tone',
 'office worker: medium skin tone',
 'man: light skin tone',
 'closed mailbox with raised flag',
 'cricket',
 'warning volcano',
 'deaf woman: medium skin tone',
 'thumbs up: medium-dark skin tone',
 'minibus',
 'wheel chair',
 'round pushpin',
 'necktie',
 'couple with heart: woman, man, medium-dark skin tone, dark skin tone',
 'man fairy: light skin tone',
 'dashing away',
 'deaf woman: light skin tone',
 'medium-light skin tone',
 'butterfly',
 'man wearing turban: dark skin tone',
 'credit card',
 'banjo',
 'intricate',
 'nut and bolt',
 'couple with heart: person, person, medium-light skin tone, medium-dark skin tone',
 'nine-thirty',
 'raised back of hand',
 'people holding hands: light skin tone, medium skin tone',
 'man in lotus position',
 'cinema',
 'growing heart',
 'kiss: woman, woman, medium skin tone',
 'woman: medium-light skin tone, blond hair',
 'man in tuxedo: medium skin tone',
 'family: woman, boy',
 'spiral notepad',
 'smartwatch',
 'foggy mountain',
 'woman running: medium-dark skin tone',
 'jar with purple content',
 'crossed flags',
 'flag: Norfolk Island',
 'statue of zeus at olympia',
 'artist: medium skin tone',
 'kiss: woman, man, medium-light skin tone',
 'horse racing: light skin tone',
 'kiss: man, man, medium-dark skin tone, medium-light skin tone',
 'tardis',
 'person: medium skin tone',
 'yellow flag',
 'shield',
 'flag: Georgia',
 'person bowing: medium-dark skin tone',
 'safety',
 'nuclear protection',
 'woman swimming: dark skin tone',
 'waffle',
 'woman lifting weights',
 'person: medium-dark skin tone, curly hair',
 'kissing face',
 'books',
 'black large square',
 'Japanese “vacancy” button',
 'man superhero: medium skin tone',
 'waving hand: medium skin tone',
 'white heart',
 'tablet',
 'woman pilot: dark skin tone',
 'cowboy hat face',
 'man pouting: medium skin tone',
 'oncoming fist: medium skin tone',
 'ewe',
 'kiss: man, man, light skin tone',
 'man vampire: light skin tone',
 'woman getting haircut: dark skin tone',
 'inbox tray',
 'judge: medium-light skin tone',
 'COOL button',
 'lady beetle',
 'kaaba',
 'wheelchair symbol',
 'mage: medium-dark skin tone',
 'ping pong',
 'prince',
 'man juggling: medium-light skin tone',
 'man raising hand: dark skin tone',
 'slightly smiling face',
 'couple with heart: woman, man',
 'man mage: dark skin tone',
 'curly loop',
 'badminton',
 'man: medium-light skin tone, white hair',
 'archive',
 'selfie: light skin tone',
 'trump',
 'woman: medium skin tone, beard',
 'turtle',
 'blossom',
 'man student: medium-dark skin tone',
 'forward',
 'accordion',
 'pinching hand: medium-light skin tone',
 'face with medical mask',
 'mirror ball',
 'Japanese “open for business” button',
 'flag: Bulgaria',
 'OK button',
 'couple with heart: man, man, medium-dark skin tone',
 'house with garden',
 'minus',
 'satellite',
 'baby angel: light skin tone',
 'man scientist: dark skin tone',
 'man: dark skin tone, white hair',
 'authority',
 'mahjong red dragon',
 'violin',
 'O button (blood type)',
 'church',
 'man: medium-light skin tone, bald',
 'reusable bag',
 'fairy: medium skin tone',
 'butter',
 'nuclear worker woman',
 'poultry leg',
 'factory worker: medium-light skin tone',
 'hand with index finger and thumb crossed',
 'woman detective',
 'woman construction worker: medium skin tone']
model_path = "stabilityai/stable-diffusion-2-1-base"
ckpt_path = "models/2-1-base-test-inference/checkpoint-54000"
pipe = StableDiffusionPipeline.from_pretrained(
    model_path,
    revision=None,
    torch_dtype=torch.float16,
)
pipe.unet.load_attn_procs(ckpt_path)
pipe.scheduler = DEISMultistepScheduler.from_config(pipe.scheduler.config)
pipe.to("cuda")
generator = torch.Generator(device="cuda").manual_seed(0)
for prompt in txt:
    image = pipe(prompt=prompt, generator = generator, guidance_scale=15.0).images[0]
    image.save(f"/opt/ml/fid/fake/{prompt}.png")


