mixed_precision: fp16
pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5 #stabilityai/stable-diffusion-2-1-base
dataset_name: soypablo/Emoji_Dataset-Openmoji #soypablo/Emoji_Dataset-Openmoji-BLIP
caption_column: text
output_dir: models/2-1-base-test-inference
resolution: 512
train_batch_size: 2
gradient_accumulation_steps: 2
max_train_steps: 30000
checkpointing_steps: 1000
learning_rate: 1e-05
lr_scheduler: cosine
lr_warmup_steps: 0
seed: 42
validation_file: ../config/validation_prompt.txt #lora.py에서의 상대경로.
validation_prompt: "a cute bunny rabbit"
report_to: wandb
#hub_model_id: soypablo/emoji-model-finetuned-lora
gradient_checkpointing: True
random_flip: True
#push_to_hub: True
wandb_project_name: sangsu_test
wandb_run_name: lora
